CREATE TABLE tb_user (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(30),
    password VARCHAR(255) NOT NULL,
    icon_url VARCHAR(255)
);

CREATE TABLE chat (
    id VARCHAR(36) PRIMARY KEY,
    name TEXT NULL,
    type VARCHAR(20) NOT NULL,
    icon_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chats_users (
    chat_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (chat_id, user_id),
    CONSTRAINT fk_chats_users_chat FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE,
    CONSTRAINT fk_chats_users_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE,
    CONSTRAINT uk_chats_users_chat_user UNIQUE (chat_id, user_id)
);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author_id VARCHAR(36) NOT NULL,
    chat_id VARCHAR(36) NOT NULL,
    CONSTRAINT fk_message_author FOREIGN KEY (author_id) REFERENCES tb_user(id),
    CONSTRAINT fk_message_chat FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE
);

CREATE INDEX idx_message_chat_id_created_at ON message(chat_id, created_at DESC);
CREATE INDEX idx_chats_users_user_id ON chats_users(user_id);